# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Adam Gross
tagline:          Development and other stuff
url:              http://grossadamm.github.io/
paginate:         1
baseurl:          /
author:
  name:           Adam Gross
  url:            https://twitter.com/grossadamm
  email:          grossadamm@gmail.com
